# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         XML-RSS-TimingBot
version:      2.02
version_from: lib/XML/RSS/TimingBot.pm
installdirs:  site
requires:
    File::Spec:                    0
    LWP::UserAgent::Determined:    0
    XML::RSS::Timing:              0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
